import { SITE_CONFIG } from "@/data/site-config";

/**
 * The shared social share card, used by every opengraph-image route.
 *
 * Until this existed there was one card, generated by src/app/opengraph-image.tsx,
 * and Next served it for all 20 pages. Every service page shared to LinkedIn or
 * Slack previewed as the homepage.
 *
 * Keep the size at 1200x630, the ratio every major platform crops to. The hexagon
 * paths are the same mark as src/app/icon.svg, itself lifted from
 * public/brand/logo.svg, and PRIMARY is the `--primary` orange from globals.css.
 *
 * **This is the easiest place on the site for stale positioning to hide, so check
 * it whenever the hero changes.** The homepage copy here used to read "We build
 * SaaS products founders can charge for", the superseded AI-native-MVP-for-founders
 * position. It survived a metadata rewrite that fixed the `openGraph` title and
 * description in layout.tsx but never looked inside the image. That matters more
 * than an ordinary stale string, because this card is what renders when the link
 * is pasted into LinkedIn, X, Bluesky or Slack, including in outbound follow-ups.
 * A rescue prospect who sees an MVP pitch decides the site is not for them before
 * clicking.
 */
export const OG_SIZE = { width: 1200, height: 630 };
export const OG_CONTENT_TYPE = "image/png";

const PRIMARY = "#fd5b38";
const BACKGROUND = "#0f0f0f";

export interface OgCardProps {
  headline: string;
  subhead: string;
  badge?: string;
  cta?: string;
}

export function OgCard({ headline, subhead, badge, cta = "Book a Call →" }: OgCardProps) {
  // Determine dynamic font sizing for headline
  let headlineFontSize = 72;
  if (headline.length > 50) {
    headlineFontSize = 52;
  } else if (headline.length > 30) {
    headlineFontSize = 60;
  }

  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        background: BACKGROUND,
        padding: "68px 80px",
        position: "relative",
      }}
    >
      {/* Top Header: Brand mark plus wordmark, and optional badge */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          width: "100%",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "20px" }}>
          <svg width="56" height="56" viewBox="-3 -3 36 36">
            <path
              fill={PRIMARY}
              d="M0 7.69285V14.3337L14.8548 6.70659L29.9281 14.3337V7.69285L14.8548 0L0 7.69285Z"
            />
            <path
              fill={PRIMARY}
              d="M0 16.128L6.95122 12.6436V19.2837L15.1463 23.2941L30 15.7335V22.2422L14.8537 30L0 22.2422V16.128Z"
            />
          </svg>
          <div style={{ display: "flex", fontSize: 40, letterSpacing: "-0.02em" }}>
            <span style={{ color: "#ffffff", fontWeight: 700 }}>alpha</span>
            <span style={{ color: "#ffffff", opacity: 0.65 }}>brackets</span>
          </div>
        </div>

        {badge && (
          <div
            style={{
              display: "flex",
              alignItems: "center",
              background: "rgba(253, 91, 56, 0.12)",
              border: "1px solid rgba(253, 91, 56, 0.35)",
              borderRadius: "9999px",
              padding: "8px 22px",
              fontSize: 20,
              fontWeight: 600,
              color: PRIMARY,
              letterSpacing: "0.05em",
              textTransform: "uppercase",
            }}
          >
            {badge}
          </div>
        )}
      </div>

      {/* Main Body: Headline and Subhead */}
      <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
        <div
          style={{
            display: "flex",
            fontSize: headlineFontSize,
            lineHeight: 1.12,
            color: "#ffffff",
            fontWeight: 700,
            letterSpacing: "-0.03em",
            maxWidth: "980px",
          }}
        >
          {headline}
        </div>
        <div
          style={{
            display: "flex",
            fontSize: 26,
            lineHeight: 1.35,
            color: "#a0a0a0",
            maxWidth: "940px",
          }}
        >
          {subhead}
        </div>
      </div>

      {/* Footer Bar with Conversion CTA */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          borderTop: "1px solid #222222",
          paddingTop: "24px",
          width: "100%",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "16px" }}>
          <div
            style={{
              display: "flex",
              width: "48px",
              height: "4px",
              background: PRIMARY,
            }}
          />
          <div
            style={{
              display: "flex",
              fontSize: 20,
              color: PRIMARY,
              textTransform: "uppercase",
              letterSpacing: "0.15em",
              fontWeight: 700,
            }}
          >
            {SITE_CONFIG.tagline}
          </div>
        </div>

        {/* Call to Action Badge (Conversion Text) */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "24px",
          }}
        >
          {cta && (
            <div
              style={{
                display: "flex",
                alignItems: "center",
                background: PRIMARY,
                color: "#ffffff",
                fontSize: 19,
                fontWeight: 700,
                padding: "10px 24px",
                borderRadius: "9999px",
                letterSpacing: "-0.01em",
              }}
            >
              {cta}
            </div>
          )}
          <div
            style={{
              display: "flex",
              fontSize: 20,
              color: "#666666",
              letterSpacing: "-0.01em",
            }}
          >
            alphabrackets.com
          </div>
        </div>
      </div>
    </div>
  );
}

