import { SITE_CONFIG } from "@/data/site-config";

/**
 * The shared social share card, used by every opengraph-image route.
 *
 * Until this existed there was one card, generated by src/app/opengraph-image.tsx,
 * and Next served it for all 20 pages. Every service page shared to LinkedIn or
 * Slack previewed as the homepage.
 *
 * Keep the size at 1200x630, the ratio every major platform crops to. The hexagon
 * paths are the same mark as src/app/icon.svg, itself lifted from
 * public/brand/logo.svg, and PRIMARY is the `--primary` orange from globals.css.
 *
 * **This is the easiest place on the site for stale positioning to hide, so check
 * it whenever the hero changes.** The homepage copy here used to read "We build
 * SaaS products founders can charge for", the superseded AI-native-MVP-for-founders
 * position. It survived a metadata rewrite that fixed the `openGraph` title and
 * description in layout.tsx but never looked inside the image. That matters more
 * than an ordinary stale string, because this card is what renders when the link
 * is pasted into LinkedIn, X, Bluesky or Slack, including in outbound follow-ups.
 * A rescue prospect who sees an MVP pitch decides the site is not for them before
 * clicking.
 */
export const OG_SIZE = { width: 1200, height: 630 };
export const OG_CONTENT_TYPE = "image/png";

const PRIMARY = "#fd5b38";
const BACKGROUND = "#0f0f0f";

interface OgCardProps {
  headline: string;
  subhead: string;
}

export function OgCard({ headline, subhead }: OgCardProps) {
  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        background: BACKGROUND,
        padding: "80px",
      }}
    >
      {/* Brand mark plus wordmark */}
      <div style={{ display: "flex", alignItems: "center", gap: "24px" }}>
        <svg width="64" height="64" viewBox="-3 -3 36 36">
          <path
            fill={PRIMARY}
            d="M0 7.69285V14.3337L14.8548 6.70659L29.9281 14.3337V7.69285L14.8548 0L0 7.69285Z"
          />
          <path
            fill={PRIMARY}
            d="M0 16.128L6.95122 12.6436V19.2837L15.1463 23.2941L30 15.7335V22.2422L14.8537 30L0 22.2422V16.128Z"
          />
        </svg>
        <div style={{ display: "flex", fontSize: 44, letterSpacing: "-0.02em" }}>
          <span style={{ color: "#ffffff", fontWeight: 700 }}>alpha</span>
          <span style={{ color: "#ffffff", opacity: 0.65 }}>brackets</span>
        </div>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: "28px" }}>
        <div
          style={{
            display: "flex",
            // Service titles run longer than the homepage headline, so the type
            // steps down once past roughly two lines at the larger size rather
            // than overflowing the card.
            fontSize: headline.length > 34 ? 62 : 76,
            lineHeight: 1.1,
            color: "#ffffff",
            fontWeight: 700,
            letterSpacing: "-0.03em",
            maxWidth: "900px",
          }}
        >
          {headline}
        </div>
        <div style={{ display: "flex", fontSize: 30, color: "#9a9a9a" }}>
          {subhead}
        </div>
      </div>

      <div style={{ display: "flex", alignItems: "center", gap: "20px" }}>
        <div
          style={{
            display: "flex",
            width: "72px",
            height: "5px",
            background: PRIMARY,
          }}
        />
        <div
          style={{
            display: "flex",
            fontSize: 24,
            color: PRIMARY,
            textTransform: "uppercase",
            letterSpacing: "0.2em",
            fontWeight: 700,
          }}
        >
          {SITE_CONFIG.tagline}
        </div>
      </div>
    </div>
  );
}
